name: Black format check

on:
  push:
    branches:
    - main

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Black Code Formatter Check
        uses: psf/black@stable
        with:
          options: "--verbose --check"
          src: "mack"
