name: CI workflow

on:
  push:
    branches:
    - main
    
jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Black Code Formatter Check
        uses: RojerGS/python-black-check@master
        with:
          line-length: '10'
          path: 'mack'
