name: Flake8 check

on:
  push:
    branches:
    - main
    
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install Poetry
      uses: snok/install-poetry@v1

    - name: Cache Poetry virtualenv
      uses: actions/cache@v1
      id: cache
      with:
        path: ~/.virtualenvs
        key: poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          poetry-${{ hashFiles('**/poetry.lock') }}
    - name: Install dependencies
      run: poetry install
      if: steps.cache.outputs.cache-hit != 'true'
    - name: flake8 Lint
      uses: py-actions/flake8@v2
      with:
        max-line-length: "88"
        plugins: "flake8-bugbear==22.12.6 pep8-naming flake8-pyproject"
