name: Flake8 check

on:
  push:
    branches:
    - main
    
    
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: flake8 Lint
      uses: py-actions/flake8@v2
      with:
        args: "--exit-zero"
        max-line-length: "88"
        ignore: "E501,E275,W503"
        plugins: "flake8-bugbear==22.12.6 pep8-naming flake8-pyproject"
